/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntGrafico;

import Codigo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Tostadora
 */
public class CBus extends javax.swing.JFrame {

    /**
     * Creates new form CBus
     */
    
    metodos met= new metodos();
    Asiento[] as ;
    DatosPersonal[] dpv = new DatosPersonal[100];
    Archivos arch = new Archivos();
    int i =0;
    private String Ruta;
    public CBus() {
        initComponents();
    }

    public String getRuta() {
        return Ruta;
    }

    public void setRuta(String Ruta) {
        this.Ruta = Ruta;
        String placa = JOptionPane.showInputDialog("Ingrese numero de placa");
        String año   = JOptionPane.showInputDialog("Ingrese Año de creacion");
        System.out.println("---"+Ruta);
        arch.crearCarpeta("Ruta\\"+Ruta,placa);
        Ruta+="\\"+placa;
        System.out.println("++++"+Ruta);
        arch.crearArchivos("Ruta\\"+Ruta, placa,año);
        arch.crearCarpeta("Ruta\\"+Ruta,"Asiento");
        arch.crearCarpeta("Ruta\\"+Ruta,"Personal");
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JCi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JCargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JEdad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        jButton3.setText("jButton3");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(538, 398));
        getContentPane().setLayout(null);

        jButton1.setText("GENERAR ASIENTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(5, 80, 170, 32);

        jButton2.setText("AGREGAR PERSONAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 190, 170, 32);

        jButton4.setText("FINALIZAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 280, 100, 30);

        jLabel1.setText("Nombre :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 70, 40);
        getContentPane().add(JNombre);
        JNombre.setBounds(270, 20, 180, 24);

        jLabel2.setText("Ci :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 60, 70, 30);

        JCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCiActionPerformed(evt);
            }
        });
        getContentPane().add(JCi);
        JCi.setBounds(270, 60, 180, 24);

        jLabel3.setText("Cargo :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 90, 60, 50);
        getContentPane().add(JCargo);
        JCargo.setBounds(270, 100, 180, 24);

        jLabel4.setText("Edad :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 130, 60, 40);
        getContentPane().add(JEdad);
        JEdad.setBounds(270, 140, 180, 24);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 250, 470, 20);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(470, 0, 20, 330);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(190, 0, 20, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.as  = met.generarAsientos();
        System.out.println("Se genero");
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DatosPersonal dp = new DatosPersonal(JNombre.getText(), JCi.getText(), JCargo.getText(), Integer.parseInt(JEdad.getText()));
        dpv[i] = dp;
        
        i++;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        DatosPersonal[] vv = new DatosPersonal[i];
        
        for (int j = 0; j < i; j++) {
            vv[j]=dpv[j];
        }
        
        Archivos arch = new Archivos();
        for (int j = 0; j < as.length; j++) {
                Asiento a = as[j];
                String data =  a.getTipo()+"\n"+a.isEstado()+"\n"+a.isSeccion();
                arch.crearArchivos("Ruta\\"+Ruta+"\\Bus\\Asiento",j+a.getTipo(), data);
                
            }
            
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JCargo;
    private javax.swing.JTextField JCi;
    private javax.swing.JTextField JEdad;
    private javax.swing.JTextField JNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
