/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntGrafico;

import Codigo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Tostadora
 */
public class CBus extends javax.swing.JFrame {

    /**
     * Creates new form CBus
     */
    
    public CBus() {
        initComponents();
    }

    private PilaRuta pilaRuta = new PilaRuta();
    private PilaPersonal pilaPersonal = new PilaPersonal();
    private PilaAsiento pilaAsiento = new PilaAsiento();
    private PilaBus pilaBus = new PilaBus();
    private PilaContratacion pilaContra = new PilaContratacion();
    private Ruta ruta;
    
    String codigo;
    String añoEmpleo;
    public void Base(Ruta cruta,PilaRuta ruta,PilaContratacion pilaC){
        this.pilaRuta = ruta;
        this.ruta = cruta;
        this.pilaContra = pilaC;
        this.codigo = JOptionPane.showInputDialog("Ingrese codigo del bus (Placa)");
        this.añoEmpleo = JOptionPane.showInputDialog("¿En qué año se compró el bus?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JCi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JEdad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        hora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(538, 398));
        getContentPane().setLayout(null);

        jButton1.setText("GENERAR ASIENTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 170, 32);

        jButton2.setText("AGREGAR PERSONAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 190, 170, 32);

        jButton4.setText("FINALIZAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 280, 100, 30);

        jLabel1.setText("Nombre :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 70, 40);
        getContentPane().add(JNombre);
        JNombre.setBounds(270, 20, 180, 24);

        jLabel2.setText("Ci :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 60, 70, 30);

        JCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCiActionPerformed(evt);
            }
        });
        getContentPane().add(JCi);
        JCi.setBounds(270, 60, 180, 24);

        jLabel3.setText("Cargo :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 90, 60, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Hora :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 70, 40);
        getContentPane().add(JEdad);
        JEdad.setBounds(270, 140, 180, 24);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 250, 470, 20);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(470, 0, 20, 250);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(190, 0, 20, 250);

        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });
        getContentPane().add(hora);
        hora.setBounds(70, 150, 40, 24);

        jLabel5.setText("Edad :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 130, 60, 40);

        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "conductor", "anfitrion" }));
        getContentPane().add(cargo);
        cargo.setBounds(270, 100, 180, 26);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel6.setText(":");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 150, 30, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 150, 50, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < 15; i++) {
            Asiento a = new Asiento("libre", "normal",true);
            pilaAsiento.adiElem(a);
        }
        for (int i = 0; i < 10; i++) {
            Asiento a = new Asiento("libre", "preferencial",true);
            pilaAsiento.adiElem(a);
        }
        for (int i = 0; i < 5; i++) {
            Asiento a = new Asiento("Ocupado", "normal",true);
            pilaAsiento.adiElem(a);
        }
        System.out.println("Se genero");
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DatosPersonal dp = new DatosPersonal(JNombre.getText(), JCi.getText(), (String)cargo.getSelectedItem(), Integer.parseInt(JEdad.getText()));
        pilaPersonal.adiElem(dp);
        
        JNombre.setText(""); 
        JCi.setText(""); 
        JEdad.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JCiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Bus b = new Bus(pilaPersonal, pilaAsiento,codigo,Integer.parseInt(añoEmpleo),Integer.parseInt(hora.getText()));
        pilaBus.adiElem(b);
        ruta.setBuses(pilaBus);
        CRuta c = new CRuta();
        System.out.println(ruta.getNombreRuta());
        c.Base(ruta.getNombreRuta(), ruta, pilaRuta, pilaContra);
        c.show();
        this.dispose();
            
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_horaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JCi;
    private javax.swing.JTextField JEdad;
    private javax.swing.JTextField JNombre;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
