/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntGrafico;

import Codigo.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Tostadora
 */
public class CParada extends javax.swing.JFrame {

    /**
     * Creates new form CParada
     */
    DefaultTableModel modelo;
    private String direccion;
    Archivos arch = new Archivos();
    Parada p;
    Pila parada = new Pila();
    
    public CParada() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Zona");
        modelo.addColumn("Calle");
        this.tabla.setModel(modelo);
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
        Ruta.setText(direccion);
    }

    
    private void Agregar(){
    
        
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Zona = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ruta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(465, 470));
        getContentPane().setLayout(null);
        getContentPane().add(Zona);
        Zona.setBounds(20, 80, 170, 24);

        jButton1.setText("FINALIZAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 370, 100, 32);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 40, 200, 380);

        jLabel2.setText("Zona");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 190, 40);

        jButton2.setText("ARGEGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 190, 100, 32);
        getContentPane().add(Nombre);
        Nombre.setBounds(20, 140, 170, 30);

        jLabel3.setText("Calle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 190, 40);

        Ruta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Ruta.setText("Ruta");
        getContentPane().add(Ruta);
        Ruta.setBounds(10, 10, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] Info = new String[2];
        Info[0]=Zona.getText();
        Info[1]=Nombre.getText();
        modelo.addRow(Info);
        Zona.setText("");
        Nombre.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CParada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CParada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CParada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CParada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CParada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Ruta;
    private javax.swing.JTextField Zona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
