/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntGrafico;

import Codigo.PilaContratacion;
import Codigo.PilaRuta;
import Codigo.metodos;

/**
 *
 * @author Lilo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(511, 294);
        setLocationRelativeTo(null);//Centramos nuestro Formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcarga = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        Lblcarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(lblcarga);
        lblcarga.setBounds(332, 292, 180, 0);

        ProgressBar.setForeground(new java.awt.Color(255, 153, 51));
        ProgressBar.setBorder(null);
        getContentPane().add(ProgressBar);
        ProgressBar.setBounds(0, 280, 512, 12);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lapazbus/img/img_05.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 260);

        Lblcarga.setText("jLabel2");
        getContentPane().add(Lblcarga);
        Lblcarga.setBounds(0, 260, 510, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Principal p = new Principal();
        p.setVisible(true);
        metodos met = new metodos();
        PilaRuta pilaRuta = new PilaRuta();
        pilaRuta.adiElem(met.crearRutaChasquipampa());
        pilaRuta.adiElem(met.crearRutaIncaLlojeta());
        pilaRuta.adiElem(met.crearRutaVillaSalome());
        PilaContratacion pilaContratacion = new PilaContratacion();
        pilaContratacion = met.crear();
        String[] data = met.Mostrar(pilaRuta);
        int indi=0;
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep (125);
                p.ProgressBar.setValue(i);
                if(indi==57){
                
                    indi=0;
                }
                p.Lblcarga.setText("Cargando sistema espere porfavor..."+(Integer.toString(i)+"% ..."+data[indi]));
                indi++;
                if(i==100){
                    p.setVisible(false);
                    
                    Inicio in = new Inicio();
                    in.Base(pilaRuta, pilaContratacion);
                    in.setVisible(true);
                    
                }
            }
        }catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lblcarga;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcarga;
    // End of variables declaration//GEN-END:variables
}
