/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntGrafico;

/**
 *
 * @author Lilo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);//Centramos nuestro Formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblcarga = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lapazbus/img/img_05.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-1, -20, 510, 330);
        getContentPane().add(lblcarga);
        lblcarga.setBounds(332, 292, 180, 0);
        getContentPane().add(ProgressBar);
        ProgressBar.setBounds(0, 262, 512, 12);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Principal p = new Principal();
        p.setVisible(true);
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep (125);
                p.ProgressBar.setValue(i);
                p.lblcarga.setText("Cargando sistema espere porfavor..."+(Integer.toString(i)+"%"));
                if(i==100){
                    p.setVisible(false);
                    Inicio in = new Inicio();
                    in.setVisible(true);
                    
                }
            }
        }catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblcarga;
    // End of variables declaration//GEN-END:variables
}
