/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntGrafico;

/**
 *
 * @author Tostadora
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(null);

        jLabel5.setText("Ver Cantidad de Buses");
        jFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 190, 70);

        jLabel6.setText("Hacer Solicitud");
        jFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 200, 240, 70);

        jLabel7.setText("Ingrese hora a verificar salida de buses");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 80, 240, 70);

        jButton5.setText("VER");
        jFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(440, 40, 80, 32);

        jTextField3.setText("jTextField1");
        jFrame1.getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 100, 160, 30);

        jButton6.setText("VER");
        jFrame1.getContentPane().add(jButton6);
        jButton6.setBounds(440, 100, 80, 30);

        jTextField4.setText("jTextField2");
        jFrame1.getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 160, 160, 30);

        jButton7.setText("VER");
        jFrame1.getContentPane().add(jButton7);
        jButton7.setBounds(440, 160, 80, 32);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jFrame1.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(270, 40, 160, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jFrame1.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(13, 310, 520, 180);

        jLabel8.setText("Ingrese parada a averiguar");
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 140, 240, 70);

        jButton8.setText("Solicitud");
        jFrame1.getContentPane().add(jButton8);
        jButton8.setBounds(280, 220, 110, 32);

        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 60));
        jFrame1.getContentPane().add(jSeparator5);
        jSeparator5.setBounds(-10, 260, 560, 20);

        jSeparator6.setPreferredSize(new java.awt.Dimension(50, 60));
        jFrame1.getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 80, 560, 10);

        jSeparator7.setPreferredSize(new java.awt.Dimension(50, 60));
        jFrame1.getContentPane().add(jSeparator7);
        jSeparator7.setBounds(0, 140, 560, 20);

        jSeparator8.setPreferredSize(new java.awt.Dimension(50, 60));
        jFrame1.getContentPane().add(jSeparator8);
        jSeparator8.setBounds(0, 200, 560, 20);

        jSeparator11.setPreferredSize(new java.awt.Dimension(50, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(549, 513));
        getContentPane().setLayout(null);

        jLabel1.setText("Ver Cantidad de Buses");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 190, 70);

        jLabel2.setText("Hacer Solicitud");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 200, 240, 70);

        jLabel3.setText("Ingrese hora a verificar salida de buses");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 240, 70);

        jButton1.setText("VER");
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 30, 80, 32);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 100, 160, 30);

        jButton2.setText("VER");
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 100, 80, 30);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 160, 160, 30);

        jButton3.setText("VER");
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 160, 80, 32);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 30, 160, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(-10, 320, 560, 190);

        jLabel4.setText("Ingrese parada a averiguar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 240, 70);

        jButton4.setText("Solicitud");
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 220, 110, 32);

        jButton9.setText("MENU");
        getContentPane().add(jButton9);
        jButton9.setBounds(440, 280, 90, 30);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-10, 150, 560, 20);
        jSeparator1.getAccessibleContext().setAccessibleDescription("");

        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 90, 560, 10);

        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 210, 560, 20);

        jSeparator9.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(0, 140, 560, 20);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(260, 0, 70, 520);

        jSeparator12.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator12);
        jSeparator12.setBounds(-10, 200, 560, 20);

        jSeparator13.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator13);
        jSeparator13.setBounds(0, 200, 560, 20);

        jSeparator14.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator14);
        jSeparator14.setBounds(0, 80, 560, 10);

        jSeparator15.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator15);
        jSeparator15.setBounds(-10, 260, 560, 20);

        jSeparator16.setPreferredSize(new java.awt.Dimension(50, 60));
        getContentPane().add(jSeparator16);
        jSeparator16.setBounds(0, 270, 560, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
